Initial Commit - models defined, crud operations defined
absenth/qsolink pull request #1
Opened 2023-09-16 14:40 UTC by absenth

Setup new poetry project for qsolink.
setup the database, models, and fastapi CRUD operations.

2023-09-16 22:04 UTC, BitMasher requested changes
at least fix the database model, but ideally add error handling too

2023-09-16 22:04 UTC, BitMasher commented on qsolink/qsolink.py
> +    db.commit()
add error handling if db commit fails

2023-09-17 01:17 UTC, absenth commented on qsolink/qsolink.py
> +
I should add versioning to each of the CRUD operations here so future changes don't cause clients to fail.

2023-09-17 01:18 UTC, absenth commented on tests/test_qsolink.py
> +
the database, qsolink, and models imports are broken.

2023-09-17 17:00 UTC, absenth commented on qsolink/qsolink.py
> +
Versioning has been added using the fastapi-versioning package.

2023-09-17 17:00 UTC, merged

2023-09-18 10:06 UTC, benediktkr commented on pyproject.toml
> +fastapi-versioning = "^0.10.0"
...interersting.

2023-09-18 10:08 UTC, benediktkr commented on qsolink/database.py
> +SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
👍

2023-09-18 10:10 UTC, benediktkr commented on qsolink/qsolink.py
> +
style comment: the `read_api` function does not have an empty line here.

2023-09-18 10:12 UTC, benediktkr commented on qsolink/qsolink.py
> +    except Exception as e:
don't catch the base `Exception` class, catch the exceptions you know/expect can happen.

if you use loguru, you can decorate your entrypoint function with `loguru` catch to log any unexoected exceotions that might happen, and then handle them in the correct places.

2023-09-18 10:12 UTC, benediktkr commented on qsolink/qsolink.py
> +
this one also start with an empty line.

2023-09-18 10:15 UTC, benediktkr commented on qsolink/qsolink.py
> +    qso_model.remarks = qso.remarks
you can add a method to your `models.Qsos` that accepts a `Qso` instance and does this

then this could look like this instead:  

```python 
qso_model.foo(qso)
```

2023-09-18 10:19 UTC, benediktkr commented on qsolink/qsolink.py
> +
```python3
    # choose better names though
    def foo(self, input_model):
        self.dateon = input_model.dateon
        # ...
        self.remarks = input_model.remarks
```

python3's dataclasses _could_ be useful, but something like this is simple enough and saves you repetition in the api

2023-09-18 10:19 UTC, benediktkr commented on qsolink/qsolink.py
> +    qso_model.remarks = qso.remarks
https://github.com/absenth/qsolink/pull/1/files#r1328517724

2023-09-18 10:20 UTC, benediktkr commented on qsolink/qsolink.py
> +    except Exception as e:
base `Exception` class

2023-09-18 10:22 UTC, benediktkr commented on pyproject.toml
> +fastapi-versioning = "^0.10.0"
move test dependencies to a `dev` group

```
poetry remove pytest 
poetry install --group dev pytest
```

iirc

2023-09-18 10:25 UTC, benediktkr commented on tests/test_qsolink.py
> +
broken how? imports look good to me, but you would need to 

```
poetry install 
# or if you have a dev dependency group in pyproject.toml
poetry install --group ddev
```

first

(it might be `--groups`, didnt check) 

i think if you use relative imports you dont have to do that, but i never remember the syntax for those correctly, something like:

```
from .qsolink.models import Qsos
```

2023-09-18 10:26 UTC, benediktkr commented on tests/test_qsolink.py
> +@pytest.fixture(scope='module')
change the `scope` to `function` (or `test` maybe? didnt look that up either) if you want each test to run with a fresh in-memory database instead of sharing them. t

the `scope` parameter decides when the fixture is created/destroyed.